import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUTPUT = resolve(process.cwd(), "output");

interface Row {
  company: string;
  subsegment: string;
  stage: string;
  aiCore: string;
  score: number;
  take: string;
}

function parseRow(line: string): Row | null {
  const cells = line.split("|").map((c) => c.trim()).filter((c) => c.length);
  if (cells.length < 6) return null;
  const score = parseInt(cells[4], 10);
  if (isNaN(score)) return null;
  return {
    company: cells[0],
    subsegment: cells[1],
    stage: cells[2],
    aiCore: cells[3],
    score,
    take: cells[5],
  };
}

function extractRowFromMemo(memo: string): Row | null {
  // find the rubric-format row at the bottom of the memo
  const lines = memo.split("\n");
  for (const line of lines) {
    if (line.includes("|") && /\|\s*\d+\s*\|/.test(line)) {
      const row = parseRow(line);
      if (row && !row.company.toLowerCase().includes("company")) return row;
    }
  }
  return null;
}

function main() {
  const files = readdirSync(OUTPUT).filter((f) => f.endsWith("-memo.md"));
  const rows: Row[] = [];
  for (const f of files) {
    const memo = readFileSync(resolve(OUTPUT, f), "utf8");
    const row = extractRowFromMemo(memo);
    if (row) rows.push(row);
    else console.warn(`[merge-map] could not extract row from ${f}`);
  }

  rows.sort((a, b) => b.score - a.score);

  const header = `# AI-Native Financial Infrastructure — Market Map

*Generated by sfv-ic-agent. Last updated: ${new Date().toISOString().slice(0, 10)}.*

| Company | Subsegment | Stage | AI-core? | Score | One-line take |
|---|---|---|---|---|---|
`;

  const body = rows
    .map((r) => `| ${r.company} | ${r.subsegment} | ${r.stage} | ${r.aiCore} | ${r.score} | ${r.take} |`)
    .join("\n");

  writeFileSync(resolve(OUTPUT, "market-map.md"), header + body + "\n");
  console.log(`[merge-map] wrote ${rows.length} rows to output/market-map.md`);
}

main();
